#!/bin/bash
TEST_SERVER_PORT=34777 
PACKAGE_NAME='sh.calabash.demoproject'
MAIN_ACTIVITY='sh.calabash.demoproject.HelloAndroidActivity'

IRBRC=.irbrc TEST_SERVER_PORT=$TEST_SERVER_PORT PACKAGE_NAME=$PACKAGE_NAME MAIN_ACTIVITY=$MAIN_ACTIVITY irb
